version: "3.5"
services:
  web:
    container_name: dockerdev
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      DD_DB_HOST: db
    # command: /server
    depends_on:
      - db
  db:
    container_name: dockerdev-db
    image: postgres:12.2-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gqlwithgo
    volumes:
      - ./scripts/postgres/schema.sql:/docker-entrypoint-initdb.d/init.sql
